#!/usr/bin/env bash
# ============================================================================
# Export the extractor tools out of the image and into the repo root, so
# people can just run them.
#
# Runs as the `extractors` service on every `docker compose up -d`. It is a
# one-shot: it copies, prints instructions, and exits 0.
#
#   <repo root>/
#     extract-data.sh     <- Linux/macOS: run this
#     extract-data.bat    <- Windows: double-click this
#     tools/
#       mapextractor vmap4extractor vmap4assembler mmaps_generator
#       lib/            <- the shared libraries those four need
#       run-tool.sh     <- runs a tool with the bundled libs
#
# WHY THE HOST OS MATTERS
#   The binaries in this image are Linux x86-64 ELF executables. On a Linux
#   host they run natively, straight off ./tools. On Windows/macOS they
#   cannot run on the host at all — Docker Desktop runs a Linux VM — so the
#   generated extract-data.* launcher runs them back inside this same image
#   instead. Either way the user runs ONE file from the repo root and the
#   output lands in ./data.
# ============================================================================
set -u

DEST="${EXPORT_DIR:-/export}"
BIN_DIR="${TC_BIN_DIR:-/opt/tc/bin}"
TOOLS="mapextractor vmap4extractor vmap4assembler mmaps_generator"
IMAGE_REF="${SERVER_IMAGE_REF:-trinitycore-3.4.3:local}"

log() { echo "[export-tools] $*"; }

if [ ! -d "$DEST" ]; then
  log "FATAL: $DEST is not mounted — check the extractors service in docker-compose.yml"
  exit 1
fi

# ---------------------------------------------------------------------------
# Skip the copy when it is already current. The image is rebuilt whenever
# upstream changes, so stamp with the binary's mtime+size rather than a
# version string the tools do not expose.
# ---------------------------------------------------------------------------
stamp_now="$(stat -c '%Y-%s' "$BIN_DIR/mapextractor" 2>/dev/null || echo unknown)"
stamp_file="$DEST/tools/.stamp"
if [ -f "$stamp_file" ] && [ "$(cat "$stamp_file" 2>/dev/null)" = "$stamp_now" ]; then
  log "tools in ./tools are already up to date — nothing to do."
  exit 0
fi

log "exporting extractor tools to the repo root ..."
mkdir -p "$DEST/tools/lib" || { log "FATAL: cannot write to $DEST"; exit 1; }

# ---------------------------------------------------------------------------
# Copy the binaries plus every non-glibc shared library they pull in, so the
# tools keep working on a Linux host whose distro has different boost/ssl
# versions than the Ubuntu 24.04 base image.
#
# glibc itself (libc/libm/libpthread/ld-linux) is deliberately NOT bundled:
# mixing a bundled libc with the host's loader is what breaks these setups.
# Everything else (boost, ssl, stdc++) is copied.
# ---------------------------------------------------------------------------
for t in $TOOLS; do
  if [ ! -x "$BIN_DIR/$t" ]; then
    log "WARNING: $BIN_DIR/$t missing from the image — skipped"
    continue
  fi
  cp -f "$BIN_DIR/$t" "$DEST/tools/$t"
  chmod 0755 "$DEST/tools/$t"

  ldd "$BIN_DIR/$t" 2>/dev/null | awk '{print $3}' | grep '^/' | while read -r so; do
    case "$(basename "$so")" in
      libc.so.*|libm.so.*|libpthread.so.*|libdl.so.*|librt.so.*|ld-linux*) continue ;;
    esac
    [ -f "$DEST/tools/lib/$(basename "$so")" ] || cp -Lf "$so" "$DEST/tools/lib/" 2>/dev/null || true
  done
done
log "  copied: $(cd "$DEST/tools" && ls mapextractor vmap4extractor vmap4assembler mmaps_generator 2>/dev/null | tr '\n' ' ')"
log "  bundled $(ls -1 "$DEST/tools/lib" 2>/dev/null | wc -l) shared libraries"

# ---------------------------------------------------------------------------
# run-tool.sh — runs one bundled tool with the bundled libs.
# ---------------------------------------------------------------------------
cat > "$DEST/tools/run-tool.sh" <<'RUNTOOL'
#!/usr/bin/env bash
# Runs one extractor tool using the libraries bundled next to it.
#   ./tools/run-tool.sh mapextractor [args...]
set -u
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tool="${1:?usage: run-tool.sh <mapextractor|vmap4extractor|vmap4assembler|mmaps_generator> [args]}"
shift
exec env LD_LIBRARY_PATH="$here/lib:${LD_LIBRARY_PATH:-}" "$here/$tool" "$@"
RUNTOOL
chmod 0755 "$DEST/tools/run-tool.sh"

# ---------------------------------------------------------------------------
# extract-data.sh — the Linux/macOS entry point, written to the REPO ROOT.
#
# It prefers the native binaries and falls back to running them inside the
# image (macOS, or a Linux host too old for these binaries).
# ---------------------------------------------------------------------------
cat > "$DEST/extract-data.sh" <<EXTRACTSH
#!/usr/bin/env bash
# ==========================================================================
#  Extract client data from a WoW 3.4.3 client.   GENERATED by the
#  'extractors' service — re-created on every 'docker compose up -d'.
#
#    ./extract-data.sh /path/to/3.4.3/client
#
#  Results land in ./data, which the servers already mount.
# ==========================================================================
set -euo pipefail

# Which image to run the tools in when this host cannot execute them
# natively: environment first, then ./.env, then the value baked at export.
BAKED_IMAGE="$IMAGE_REF"
IMAGE="\${SERVER_IMAGE:-}"
EXTRACTSH
cat >> "$DEST/extract-data.sh" <<'EXTRACTSH'
HERE="$(cd "$(dirname "$0")" && pwd)"

if [ -z "$IMAGE" ] && [ -f "$HERE/.env" ]; then
  IMAGE="$(sed -n 's/^[[:space:]]*SERVER_IMAGE[[:space:]]*=[[:space:]]*//p' "$HERE/.env" \
            | tail -n1 | sed -e 's/[[:space:]]*#.*$//' -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'$/\1/")"
fi
[ -n "$IMAGE" ] || IMAGE="$BAKED_IMAGE"

# ---------------------------------------------------------------------------
# `docker run` pulls anything it does not have locally, and a plain name like
# trinitycore-3.4.3:local is not on any registry — Docker Hub then answers
#   pull access denied for trinitycore-3.4.3, repository does not exist or
#   may require 'docker login'
# So: look at the local image cache first and never start a blind pull for a
# local-only name. Registry names (ghcr.io/..., localhost:5000/...) are pulled.
# ---------------------------------------------------------------------------
ensure_image() {
  docker version >/dev/null 2>&1 \
    || { echo "ERROR: the Docker engine is not reachable — start Docker Desktop (or the docker daemon) and re-run."; exit 1; }
  docker image inspect "$IMAGE" >/dev/null 2>&1 && return 0

  case "$IMAGE" in
    *.*/*|*:*/*)                                   # <host>[:port]/name → a registry
      echo "   $IMAGE is not cached yet — pulling it"
      docker pull "$IMAGE" && return 0
      echo "ERROR: could not pull $IMAGE"
      echo "       GHCR packages are private by default: make it Public, or run"
      echo "       'docker login ${IMAGE%%/*}' first."
      exit 1 ;;
  esac

  echo
  echo "ERROR: this Docker engine has no image named '$IMAGE'."
  echo "       That is a local-only name — no registry serves it, so Docker"
  echo "       cannot download it (hence 'pull access denied for ${IMAGE%%:*}')."
  echo
  echo "   Fix it one of two ways:"
  echo "     a) build it here, once (25-45 min):   docker compose build"
  echo "     b) point at the CI image in .env, then re-run:"
  echo "          SERVER_IMAGE=ghcr.io/<you>/<repo>:latest"
  echo "          SERVER_PULL_POLICY=always"
  echo
  if [ -t 0 ] && [ -f "$HERE/docker-compose.yml" ]; then
    printf "   Build it now? [y/N] "
    read -r ans
    case "$ans" in
      [yY]*) ( cd "$HERE" && docker compose build ) || { echo "ERROR: the build failed."; exit 1; } ;;
      *)     exit 1 ;;
    esac
  else
    exit 1
  fi
}

CLIENT="${1:-}"
if [ -z "$CLIENT" ]; then
  echo "usage: $0 /path/to/3.4.3/client"
  echo "  (the folder containing Wow.exe and a Data/ subfolder)"
  exit 1
fi
CLIENT="$(cd "$CLIENT" && pwd)"
[ -d "$CLIENT/Data" ] || { echo "ERROR: $CLIENT has no Data/ subfolder — that is not a WoW client folder."; exit 1; }

# Can the exported native binaries run on this host?
NATIVE=no
if [ -x "$HERE/tools/mapextractor" ] \
   && LD_LIBRARY_PATH="$HERE/tools/lib" "$HERE/tools/mapextractor" -? >/dev/null 2>&1; then
  NATIVE=yes
fi

echo "== extracting from $CLIENT =="
echo "   mode: $([ "$NATIVE" = yes ] && echo 'native (./tools)' || echo "docker ($IMAGE)")"
echo "   this takes 1-4 hours and ~25 GB of free disk"
echo

# The tools are hardcoded to read/write the CURRENT directory, so everything
# runs with the client folder as cwd, then we move the results into ./data.
if [ "$NATIVE" = yes ]; then
  run() { ( cd "$CLIENT" && LD_LIBRARY_PATH="$HERE/tools/lib" "$HERE/tools/$1" "${@:2}" ); }
else
  command -v docker >/dev/null 2>&1 || { echo "ERROR: these binaries can't run on this host and docker is not installed."; exit 1; }
  ensure_image
  run() { docker run --rm -v "$CLIENT:/client" -w /client --entrypoint "/opt/tc/bin/$1" "$IMAGE" "${@:2}"; }
fi

echo "--- 1/4 mapextractor (dbc, maps, cameras, gt)"
run mapextractor
echo "--- 2/4 vmap4extractor (raw model data -> Buildings/)"
# The tool refuses to start if Buildings/ still holds dir/dir_bin from an
# earlier interrupted run.
rm -rf "$CLIENT/Buildings"
run vmap4extractor
echo "--- 3/4 vmap4assembler (Buildings -> vmaps)"
# ARGV is <raw data dir> <vmap dest dir>; passing "." produces no vmaps.
rm -rf "$CLIENT/vmaps"
run vmap4assembler Buildings vmaps
echo "--- 4/4 mmaps_generator (slow: hours)"
run mmaps_generator
rm -rf "$CLIENT/Buildings"

echo
echo "== moving results into ./data =="
mkdir -p "$HERE/data"
for d in dbc maps vmaps mmaps gt cameras; do
  if [ -d "$CLIENT/$d" ]; then
    rm -rf "$HERE/data/$d"
    mv "$CLIENT/$d" "$HERE/data/$d"
    echo "   data/$d ($(du -sh "$HERE/data/$d" | cut -f1))"
  else
    echo "   WARNING: $d was not produced" >&2
  fi
done

missing=""
for d in dbc maps vmaps mmaps gt; do
  [ -d "$HERE/data/$d" ] || missing="$missing $d"
done
if [ -n "$missing" ]; then
  echo
  echo "ERROR: required data is missing:$missing — the server will not start."
  exit 1
fi

echo
echo "== done — worldserver picks this up within 60 s =="
echo "   (or run: docker compose restart worldserver)"
EXTRACTSH
chmod 0777 "$DEST/extract-data.sh"

# ---------------------------------------------------------------------------
# extract-data.bat — the Windows entry point, written to the REPO ROOT.
#
# The exported ELF binaries cannot execute on Windows, so this drives the
# tools through the image the user has already built. Written with CRLF.
# ---------------------------------------------------------------------------
{
cat <<EXTRACTBAT
@echo off
setlocal enabledelayedexpansion
title WoW 3.4.3 - Extract client data
set "BAKED_IMAGE=$IMAGE_REF"
EXTRACTBAT
cat <<'EXTRACTBAT'

rem  Which image do the servers run? Precedence: (1) SERVER_IMAGE in this
rem  shell, (2) the .env file, (3) the value baked in at export time.
rem  Double-clicking does not read .env, so load the line here - otherwise this
rem  launcher would drive a different image than the stack actually runs.
if "%SERVER_IMAGE%"=="" (
  if exist "%~dp0.env" for /f "usebackq tokens=1,* delims==" %%A in (`findstr /B /C:"SERVER_IMAGE=" "%~dp0.env"`) do set "SERVER_IMAGE=%%B"
)
if "%SERVER_IMAGE%"=="" set "SERVER_IMAGE=%BAKED_IMAGE%"
rem  strip quotes an editor may have left in .env (%..":"=% removes every ")
set "SERVER_IMAGE=%SERVER_IMAGE:"=%"

rem ==========================================================================
rem  Extract client data from a WoW 3.4.3 client.  GENERATED by the
rem  'extractors' service - re-created on every 'docker compose up -d'.
rem
rem  Drag your client folder onto this file, or run:
rem      extract-data.bat "C:\Games\WoW 3.4.3"
rem
rem  The extractor binaries are Linux executables, so this runs them inside
rem  the Docker image you already built. Docker Desktop must be running.
rem ==========================================================================

set "CLIENT=%~1"
if "%CLIENT%"=="" (
  echo(
  echo  Usage: drag your WoW 3.4.3 folder onto this file,
  echo         or run:  extract-data.bat "C:\Games\WoW 3.4.3"
  echo(
  echo  That is the folder containing Wow.exe and a Data subfolder.
  goto :fail
)
if not exist "%CLIENT%\Data" (
  echo  ERROR: "%CLIENT%" has no Data subfolder.
  echo  That does not look like a WoW client folder.
  goto :fail
)

docker version >nul 2>&1
if errorlevel 1 (
  echo  ERROR: Docker is not running. Start Docker Desktop and try again.
  goto :fail
)

rem  The tools are run INSIDE the image, so the image must be in the local
rem  Docker cache. A plain name (no registry host) is not published anywhere,
rem  so `docker run` cannot download it - that is exactly what
rem  "pull access denied for trinitycore-3.4.3" means. Check before starting,
rem  and offer to build instead of failing 2 seconds in.
docker image inspect "%SERVER_IMAGE%" >nul 2>&1
if not errorlevel 1 goto :image_ready
echo(
echo  This Docker engine has no image named "%SERVER_IMAGE%".
echo  It is built from this repo - no registry serves such a plain name, so
echo  Docker cannot download it (that is the "pull access denied" error).
echo(
choice /C YN /M "Build it now - 25-45 minutes, only the first time"
if errorlevel 2 (
  echo(
  echo  Not building. Either run "docker compose build" yourself, or set in .env:
  echo      SERVER_IMAGE=ghcr.io/your-user/your-repo:latest
  echo      SERVER_PULL_POLICY=always
  goto :fail
)
echo(
docker compose --project-directory "%~dp0." build
if errorlevel 1 goto :fail
:image_ready

echo(
echo  Client: %CLIENT%
echo  Image : %SERVER_IMAGE%
echo(
echo  This takes 1-4 hours and needs ~25 GB of free disk space.
echo  Almost all of it is the last step. Ctrl+C is safe - just re-run.
echo(
choice /C YN /M "Start extraction now"
if errorlevel 2 goto :cancelled
echo(

set "DRUN=docker run --rm -v "%CLIENT%":/client -w /client --entrypoint"

echo  [1/4] mapextractor  (dbc, maps, cameras, gt)
%DRUN% /opt/tc/bin/mapextractor "%SERVER_IMAGE%"
if errorlevel 1 goto :toolfail

echo  [2/4] vmap4extractor  (raw model data)
if exist "%CLIENT%\Buildings" rd /s /q "%CLIENT%\Buildings"
%DRUN% /opt/tc/bin/vmap4extractor "%SERVER_IMAGE%"
if errorlevel 1 goto :toolfail

echo  [3/4] vmap4assembler  (Buildings -^> vmaps)
if exist "%CLIENT%\vmaps" rd /s /q "%CLIENT%\vmaps"
%DRUN% /opt/tc/bin/vmap4assembler "%SERVER_IMAGE%" Buildings vmaps
if errorlevel 1 goto :toolfail

echo  [4/4] mmaps_generator  (the slow one)
%DRUN% /opt/tc/bin/mmaps_generator "%SERVER_IMAGE%"
if errorlevel 1 goto :toolfail

if exist "%CLIENT%\Buildings" rd /s /q "%CLIENT%\Buildings"

echo(
echo  == moving results into .\data ==
if not exist "%~dp0data" mkdir "%~dp0data"
for %%D in (dbc maps vmaps mmaps gt cameras) do (
  if exist "%CLIENT%\%%D" (
    if exist "%~dp0data\%%D" rd /s /q "%~dp0data\%%D"
    move /y "%CLIENT%\%%D" "%~dp0data\" >nul
    echo     data\%%D
  ) else (
    echo     WARNING: %%D was not produced
  )
)

set "MISSING="
for %%D in (dbc maps vmaps mmaps gt) do (
  if not exist "%~dp0data\%%D" set "MISSING=!MISSING! %%D"
)
if defined MISSING (
  echo(
  echo  ERROR: required data is missing:!MISSING!
  echo  The server will not start. Scroll up for errors.
  goto :fail
)

echo(
echo  == done - worldserver picks this up within 60 seconds ==
echo     (or run: docker compose restart worldserver)
echo(
pause
exit /b 0

:toolfail
echo(
echo  A tool failed (exit %errorlevel%).
echo  Common causes: not a 3.4.3 WotLK Classic client (3.3.5a/MPQ is not
echo  supported), an incomplete client download, or not enough disk space.
goto :fail

:cancelled
echo  Cancelled - nothing was changed.
pause
exit /b 0

:fail
echo(
pause
exit /b 1
EXTRACTBAT
} | sed 's/$/\r/' > "$DEST/extract-data.bat"
chmod 0666 "$DEST/extract-data.bat"

echo "$stamp_now" > "$stamp_file"
chmod -R a+rwX "$DEST/tools" 2>/dev/null || true

log ""
log "=============================================================="
log " Extractor tools are ready in the repo root."
log ""
log "   Linux / macOS :  ./extract-data.sh /path/to/3.4.3/client"
log "   Windows       :  drag your client folder onto extract-data.bat"
log ""
log " The raw tools are in ./tools if you'd rather run them yourself."
log " Output lands in ./data and worldserver picks it up automatically."
log "=============================================================="
exit 0
